language: node_js

node_js:
  - "7.10"

# S: Build Lifecycle
install:
  - npm install hexo-cli -g
  - npm install hexo-deployer-git
  - npm install hexo --no-optional
  - npm install

#before_script:
  - npm install gulp --save
  - npm install minimatch --save
  - npm install hexo-renderer-stylus --save
  - npm install hexo-renderer-marked -g --save
  - npm install hexo-algolia --save

script:
  - hexo v
  - hexo clean
  - hexo g
  - hexo algolia
  - gulp

after_script:
  - cd ./public
  - git init
  - git config user.name "mcknote"
  - git config user.email "kiminire@gmail.com"
  - git add .
  - git commit -m "Blog Update From Travis-CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# E: Build LifeCycle

branches:
  only:
    - host
env:
 global:
   - GH_REF: github.com/mcknote/mcknote.github.io.git
